#!/usr/bin/env python3
"""
Log Analysis with Regular Expressions Coursera Activity

Introduction
Imagine your company uses a server that runs a service called ticky,
an internal ticketing system. The service logs events to syslog,
both when it runs successfully and when it encounters errors.

The service's developers need your help getting some information
from those logs so that they can better understand how their software is used and how to improve it.
So, for this lab, you'll write some automation scripts that will process the system log
and generate reports based on the information extracted from the log files.

What you'll do
Use regex to parse a log file
Append and modify values in a dictionary
Write to a file in CSV format
Move files to the appropriate directory for use with the CSV->HTML converter
You'll have 90 minutes to complete this lab.

Generate reports
Now, we're going to practice creating a script, named ticky_check.py,
that generates two different reports from this internal ticketing system log file i.e., syslog.log.
This script will create the following reports:

- The ranking of errors generated by the system: A list of all the error messages logged and
how many times each error was found, sorted by the most common error to the least common error.
This report doesn't take into account the users involved.
- The user usage statistics for the service: A list of all users that have used the system,
including how many info messages and how many error messages they've generated.
This report is sorted by username.
34.148.209.68
"""

import csv
import operator
import re

error_counts = {}
user_stats = {}

with open("syslog.log", encoding="UTF-8") as file:
    for line in file:
        error_match = re.search(r"ticky: ERROR ([\w ']*) \(([\w.]+)\)", line)
        if error_match:
            error_message = error_match.group(1)
            user = error_match.group(2)
            # add error in the error_counts dict
            if error_message in error_counts:
                error_counts[error_message] += 1
            else:
                error_counts[error_message] = 1
            # add error count in user_stats
            if user not in user_stats:
                user_stats[user] = {"INFO": 0, "ERROR": 0}
            user_stats[user]["ERROR"] += 1
            continue

        info_match = re.search(r"ticky: INFO [\w ]* [\W]+[\d]*[\W]+([\w.]+)", line)
        if info_match:
            user = info_match.group(1)
            if user not in user_stats:
                user_stats[user] = {"INFO": 0, "ERROR": 0}
            user_stats[user]["INFO"] += 1

s_user_stats = sorted(user_stats.items())
s_error_counts = sorted(error_counts.items(), key=operator.itemgetter(1), reverse=True)

# Writing Error Count in CSV File
with open("error_message.csv", "w", encoding="UTF-8") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["Error", "Count"])
    for error, count in s_error_counts:
        writer.writerow([error, count])

with open("user_statistics.csv", "w", encoding="UTF-8") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["Username", "INFO", "ERROR"])
    for requestor, stats in s_user_stats:
        writer.writerow([requestor, stats["INFO"], stats["ERROR"]])
