name: Lint Code Base

on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge:
      needs: run-lint
      # Only run if it's a PR AND the target branch is 'main'
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Enable Auto-Merge
          run: gh pr merge --auto --squash --delete-branch "$PR_URL"
          env:
            PR_URL: ${{ github.event.pull_request.html_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Delete Head Branch
          if: success() # Only delete if the automerge was successful
          run: |
            gh pr close "$PR_URL" --delete-branch
          env:
            PR_URL: ${{ github.event.pull_request.html_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
